{{- $isS3 := eq .Values.registry.storage.mode "s3" }}
apiVersion: apps/v1
kind: {{ if $isS3 }}Deployment{{ else }}StatefulSet{{ end }}
metadata:
  name: {{ include "ephemeron.registry.fullname" . }}
  labels:
    {{- include "ephemeron.registry.labels" . | nindent 4 }}
spec:
  {{- if not $isS3 }}
  serviceName: {{ include "ephemeron.registry.fullname" . }}
  {{- end }}
  replicas: {{ if $isS3 }}{{ .Values.registry.replicas }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "ephemeron.registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry/secret.yaml") . | sha256sum }}
      labels:
        {{- include "ephemeron.registry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: registry
          image: {{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}
          ports:
            - containerPort: 5000
              name: registry
            {{- if .Values.registry.metrics.enabled }}
            - containerPort: 5001
              name: metrics
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
            {{- if not $isS3 }}
            - name: data
              mountPath: /var/lib/registry
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "ephemeron.registry.fullname" . }}-config
  {{- if not $isS3 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.registry.storage.filesystem.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.registry.storage.filesystem.size }}
  {{- end }}
