{{- $isS3 := eq .Values.registry.storage.mode "s3" }}
apiVersion: apps/v1
kind: {{ if $isS3 }}Deployment{{ else }}StatefulSet{{ end }}
metadata:
  name: {{ .Release.Name }}-registry
spec:
  {{- if not $isS3 }}
  serviceName: {{ .Release.Name }}-registry
  {{- end }}
  replicas: {{ if $isS3 }}{{ .Values.registry.replicas }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-registry
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-registry
    spec:
      containers:
        - name: registry
          image: {{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}
          ports:
            - containerPort: 5000
              name: registry
            {{- if .Values.registry.metrics.enabled }}
            - containerPort: 5001
              name: metrics
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
            {{- if not $isS3 }}
            - name: data
              mountPath: /var/lib/registry
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-registry-config
  {{- if not $isS3 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.registry.storage.filesystem.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.registry.storage.filesystem.size }}
  {{- end }}
