{{- if and .Values.registry.metrics.enabled .Values.registry.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ephemeron.registry.fullname" . }}-metrics
  labels:
    {{- include "ephemeron.registry.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ephemeron.registry.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5001
      targetPort: metrics
      name: metrics
{{- end }}
