---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
spec:
  selector:
    app: {{ .Release.Name }}-registry
  ports:
    - port: 5000
      targetPort: registry
      name: registry
