{{- if and .Values.registry.metrics.enabled .Values.registry.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: {{ .Release.Name }}-registry
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-registry
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
