{{- if .Values.manager.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ephemeron.manager.fullname" . }}-metrics
  labels:
    {{- include "ephemeron.manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ephemeron.manager.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9090
      targetPort: internal
      name: metrics
{{- end }}
