{{- if .Values.manager.metrics.serviceMonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-manager-metrics
  labels:
    app: {{ .Release.Name }}-manager
spec:
  selector:
    app: {{ .Release.Name }}-manager
  ports:
    - port: 9090
      targetPort: internal
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    app: {{ .Release.Name }}-manager
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-manager
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
